### ISSUE TITLE
Docker run command issue

### ISSUE THREAD

**Issue by alfonsocatanzaro** [ragnarstolsmark/Rstolsmark.WakeOnLanServer#2]
Hi Ragnar,
thank you for your work.
I've mounted the docker image on a ubuntu server using the command as you have reported on https://hub.docker.com/r/rstolsmark/wakeonlanserver but it doesn't send magic packet.
I've found a solution, I have addded --network=host to the command like this:
```bash
docker run -d \
 -p 80:80 \
 -e ASPNETCORE_PasswordAuthenticationOptions__HashedPassword=<hash>
 -e ASPNETCORE_PasswordAuthenticationOptions__Realm="Username" \
 --name wakeonlanserver \
 --mount source=wakeonlanserver,target=/data \
 --restart always \
 --network=host \
rstolsmark/wakeonlanserver
```
It worked form me! It can help other people.
Thanks.
Alfonso.

**Comment by ragnarstolsmark** [comment]
Good catch, I have updated the command on docker hub.
